//! FORK(byok): all BYOK-fork update logic lives in this file.
//! Upstream files only contain one-line hooks into here, so upstream merges
//! stay conflict-free. Upstream's `VERSION`/GCS channel is never consulted
//! for fork installs: the source of truth is this repo's `byok-v*` releases.

use anyhow::Result;

use crate::version::UpdateConfig;

/// Installer string persisted by the fork's `install.ps1`.
pub const INSTALLER: &str = "byok";
/// Release tag prefix. The bare semver after the prefix is the comparable version.
pub const TAG_PREFIX: &str = "byok-v";
// Release tag baked in by CI (`BYOK_RELEASE` env). Absent for source builds.
// Generated by build.rs into `OUT_DIR` (not `option_env!`): a tag-only
// change must alter the compiled sources, or cargo/sccache would serve a
// stale object stamped with the previous tag.
// (Plain comments: rustdoc ignores docs on macro invocations.)
include!(concat!(env!("OUT_DIR"), "/byok_release.rs"));
/// Default update source; overridable via `GROK_BYOK_REPO` (tests, forks-of-fork).
pub const DEFAULT_REPO: &str = "ukjent7/grok-build";

fn env_repo() -> String {
    std::env::var("GROK_BYOK_REPO")
        .map(|v| v.trim().to_string())
        .ok()
        .filter(|v| !v.is_empty())
        .unwrap_or_else(|| DEFAULT_REPO.to_string())
}

/// Release tag of the running binary, if it is a tagged fork build.
pub fn release_tag() -> Option<&'static str> {
    match RELEASE {
        Some(tag) if !tag.is_empty() && tag.starts_with(TAG_PREFIX) => Some(tag),
        _ => None,
    }
}

/// Bare semver of the running fork release (e.g. `"0.1.4"`), if tagged.
pub fn release_semver() -> Option<String> {
    normalize_tag(release_tag()?)
}

/// Old fork installs persist `installer = "internal"`; a tagged fork binary
/// must still resolve to the fork source so it can never drift to official.
pub fn is_byok_install(installer: &str) -> bool {
    installer == INSTALLER || (installer == "internal" && release_tag().is_some())
}

/// Installed version on the fork axis. Tagged builds report their release;
/// source builds fall back to the Cargo version (which then matches the
/// no-network fallback in [`fetch_latest`], i.e. "already up to date").
pub fn installed_for(installer: &str) -> String {
    if is_byok_install(installer) {
        if let Some(v) = release_semver() {
            return v;
        }
    }
    crate::version::get_installed_grok_version()
}

/// `"byok-v0.1.4"` -> `Some("0.1.4")`; anything else -> `None`.
pub fn normalize_tag(tag: &str) -> Option<String> {
    let bare = tag.strip_prefix(TAG_PREFIX)?;
    semver::Version::parse(bare).ok()?;
    Some(bare.to_string())
}

/// Accept `"byok-v0.1.4"`, `"v0.1.4"` and `"0.1.4"` as `--version` pins.
/// Unknown shapes pass through so downstream validation errors as before.
pub fn normalize_pin(pin: &str) -> String {
    let pin = pin.trim();
    if let Some(bare) = pin.strip_prefix(TAG_PREFIX) {
        return bare.to_string();
    }
    if let Some(bare) = pin.strip_prefix('v') {
        if semver::Version::parse(bare).is_ok() {
            return bare.to_string();
        }
    }
    pin.to_string()
}

/// Latest stable fork release as bare semver, semver-max over non-draft,
/// non-prerelease `byok-v*` tags.
/// Paginates (100 per page, up to 5 pages) so the max is not truncated once the
/// repo holds more releases than fit on one page.
pub async fn fetch_latest() -> Result<String> {
    // Source builds carry no release tag; without a network-free answer the
    // updater would compare the Cargo version against the fork axis.
    if release_tag().is_none() {
        return Ok(crate::version::get_installed_grok_version());
    }
    let repo = env_repo();
    let mut last_err: Option<anyhow::Error> = None;
    for attempt in 0..=3 {
        if attempt > 0 {
            tokio::time::sleep(std::time::Duration::from_secs(1 << (attempt - 1))).await;
        }
        match fetch_all_tags(&repo).await.and_then(|tags| {
            pick_latest(&tags).ok_or_else(|| anyhow::anyhow!("no {TAG_PREFIX}* releases in {repo}"))
        }) {
            Ok(v) => return Ok(v),
            Err(e) => last_err = Some(e),
        }
    }
    Err(last_err.unwrap_or_else(|| anyhow::anyhow!("no BYOK releases found")))
}

#[derive(serde::Deserialize)]
struct GhRelease {
    tag_name: String,
    #[serde(default)]
    draft: bool,
}

async fn fetch_all_tags(repo: &str) -> Result<Vec<String>> {
    let mut tags = Vec::new();
    for page in 1..=5 {
        let url =
            format!("https://api.github.com/repos/{repo}/releases?per_page=100&page={page}");
        let page_tags = fetch_tags_once(&url).await?;
        let done = page_tags.len() < 100;
        tags.extend(page_tags);
        if done {
            break;
        }
    }
    Ok(tags)
}

async fn fetch_tags_once(url: &str) -> Result<Vec<String>> {
    let mut builder = xai_grok_extra_ca::build_reqwest_client(|b| {
        b.timeout(std::time::Duration::from_secs(15))
    })?
    .get(url)
    .header("User-Agent", "grok-build-byok-updater")
    .header("Accept", "application/vnd.github+json");
    if let Ok(token) = std::env::var("GITHUB_TOKEN") {
        let token = token.trim().to_string();
        if !token.is_empty() {
            builder = builder.bearer_auth(token);
        }
    }
    let resp = builder.send().await?;
    if !resp.status().is_success() {
        anyhow::bail!("GitHub releases fetch failed: HTTP {}", resp.status());
    }
    let releases: Vec<GhRelease> = resp.json().await?;
    Ok(releases
        .into_iter()
        .filter(|r| !r.draft)
        .map(|r| r.tag_name)
        .collect())
}

/// Latest stable fork release as bare semver: semver-max over non-prerelease
/// `byok-v*` tags. Prereleases never become the default update target; pinned
/// installs can still target one explicitly via [`normalize_pin`].
fn pick_latest(tags: &[String]) -> Option<String> {
    tags.iter()
        .filter_map(|t| {
            let bare = normalize_tag(t)?;
            semver::Version::parse(&bare)
                .ok()
                .filter(|v| !v.is_prerelease())
                .map(|_| bare)
        })
        .max_by(|a, b| {
            semver::Version::parse(a)
                .unwrap()
                .cmp(&semver::Version::parse(b).unwrap())
        })
}

/// Download asset name for this platform (matches `byok-build.yml` ARTIFACT).
pub fn asset_name() -> Result<&'static str> {
    let (os, arch) = super::auto_update::detect_platform()?;
    match (os, arch) {
        ("windows", "x86_64") => Ok("xai-grok-pager-windows-x64"),
        ("macos", "aarch64") => Ok("xai-grok-pager-macos-arm64"),
        _ => anyhow::bail!("No BYOK prebuilt binary for {os}-{arch}"),
    }
}

/// Download and activate the fork release. Returns the bare semver activated.
pub async fn install(
    target: Option<&str>,
    _update_config: &UpdateConfig,
) -> Result<String> {
    let version = match target {
        Some(v) => {
            let bare = normalize_pin(v);
            semver::Version::parse(&bare)
                .map_err(|_| anyhow::anyhow!("invalid version format: '{v}'"))?;
            bare
        }
        None => fetch_latest().await?,
    };
    // Source-build fallback resolves to a Cargo version with no matching tag.
    if release_tag().is_none() && target.is_none() {
        anyhow::bail!("no BYOK release tag in this build; reinstall via install.ps1");
    }
    let repo = env_repo();
    let tag = format!("{TAG_PREFIX}{version}");
    let asset = asset_name()?;
    let (os, arch) = super::auto_update::detect_platform()?;
    let platform = format!("{os}-{arch}");
    let url = format!("https://github.com/{repo}/releases/download/{tag}/{asset}");

    let grok_home = xai_grok_shell::util::grok_home::grok_home();
    let download_dir = grok_home.join("downloads");
    let bin_dir = grok_home.join("bin");
    tokio::fs::create_dir_all(&download_dir).await?;
    tokio::fs::create_dir_all(&bin_dir).await?;

    // Versioned filename keeps the managed-symlink disk probe working.
    let binary_path = download_dir.join(format!("grok-{version}-{platform}"));

    eprintln!("  Downloading grok {tag} ({platform}) from {repo}...");
    // FORK(byok): point users whose network cannot reach GitHub at the
    // jsDelivr-served installer, which carries its own mirror fallback.
    super::auto_update::download_with_progress(&url, &binary_path).await.map_err(|e| {
        anyhow::anyhow!(
            "{e:#}\n  hint: if GitHub is unreachable, reinstall via install.ps1 instead:\n    irm https://cdn.jsdelivr.net/gh/{repo}@main/install.ps1 | iex"
        )
    })?;
    // FORK(byok): install.ps1 verifies its download; the in-app path must not be weaker.
    verify_sha256(&repo, &tag, &asset, &binary_path).await?;
    super::auto_update::smoke_test_binary(&binary_path)
        .await
        .map_err(|e| anyhow::anyhow!("{e:#}"))?;
    super::auto_update::swap_managed_bin_links(&binary_path, &bin_dir).await?;
    super::auto_update::remove_stale_pager(&bin_dir).await;

    #[cfg(unix)]
    {
        let latest_path = download_dir.join("grok-latest");
        let rel_target =
            super::auto_update::relative_symlink_target(&binary_path, &latest_path);
        if let Err(e) = super::auto_update::atomic_symlink_swap(&rel_target, &latest_path).await {
            tracing::warn!("Failed to update grok-latest symlink: {e}");
        }
    }

    eprintln!();
    super::auto_update::cleanup_old_downloads(&download_dir, "grok", &version).await;
    super::auto_update::cleanup_old_downloads(&download_dir, "grok-pager", &version).await;

    let _ = xai_grok_shell::util::config::update_config(|st| {
        st.cli.installer = Some(INSTALLER.to_string());
    })
    .await;

    Ok(version)
}

/// FORK(byok): verify the downloaded release binary against SHA256 before it is
/// activated. Trust order mirrors `install.ps1`: the repo-tree copy over
/// raw.githubusercontent.com is the anchor (a tampered release asset cannot forge
/// it), then the release-asset copy next to the binary. A missing checksum aborts
/// unless `GROK_ALLOW_UNVERIFIED=1` is set explicitly; a mismatch always aborts.
async fn verify_sha256(
    repo: &str,
    tag: &str,
    asset: &str,
    binary_path: &std::path::Path,
) -> Result<()> {
    let checksum_urls = [
        format!("https://raw.githubusercontent.com/{repo}/main/checksums/{tag}/{asset}.sha256"),
        format!("https://github.com/{repo}/releases/download/{tag}/{asset}.sha256"),
    ];
    let mut expected: Option<String> = None;
    for url in checksum_urls {
        let Ok(text) = fetch_text(&url).await else {
            continue;
        };
        // Both sources are plain `sha256sum` output; the per-asset `.sha256`
        // is the bare hash, the tree also holds a combined SHA256SUMS.
        let hash = text
            .lines()
            .next()
            .unwrap_or_default()
            .split_whitespace()
            .next()
            .unwrap_or_default()
            .to_ascii_lowercase();
        if is_sha256_hex(&hash) {
            expected = Some(hash);
            break;
        }
    }
    let Some(expected) = expected else {
        if std::env::var("GROK_ALLOW_UNVERIFIED").is_ok_and(|v| v.trim() == "1") {
            tracing::warn!("GROK_ALLOW_UNVERIFIED=1: installing without a SHA256 checksum");
            return Ok(());
        }
        let _ = tokio::fs::remove_file(binary_path).await;
        anyhow::bail!(
            "no SHA256 checksum found for {tag}/{asset}; refusing to install an unverified \
             binary (set GROK_ALLOW_UNVERIFIED=1 to override)"
        );
    };
    let bytes = tokio::fs::read(binary_path).await?;
    let actual: String = sha2::Sha256::digest(&bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();
    if actual != expected {
        let _ = tokio::fs::remove_file(binary_path).await;
        anyhow::bail!(
            "SHA256 mismatch for {asset} (expected {expected}, got {actual}); \
             the download may be corrupt or tampered"
        );
    }
    Ok(())
}

fn is_sha256_hex(s: &str) -> bool {
    s.len() == 64 && s.chars().all(|c| c.is_ascii_hexdigit())
}

/// Fetch a small text file (a checksum) with the same TLS/CA settings as the releases API.
async fn fetch_text(url: &str) -> Result<String> {
    let mut builder = xai_grok_extra_ca::build_reqwest_client(|b| {
        b.timeout(std::time::Duration::from_secs(15))
    })?
    .get(url)
    .header("User-Agent", "grok-build-byok-updater");
    // raw.githubusercontent.com needs no token for public repos; private
    // forks-of-fork do, so pass GITHUB_TOKEN through like fetch_tags_once.
    if let Ok(token) = std::env::var("GITHUB_TOKEN") {
        let token = token.trim().to_string();
        if !token.is_empty() {
            builder = builder.bearer_auth(token);
        }
    }
    let resp = builder.send().await?;
    if !resp.status().is_success() {
        anyhow::bail!("checksum fetch failed: HTTP {}", resp.status());
    }
    Ok(resp.text().await?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_tag_round_trips() {
        assert_eq!(normalize_tag("byok-v0.1.4").as_deref(), Some("0.1.4"));
        assert_eq!(
            normalize_tag("byok-v0.1.4-alpha.1").as_deref(),
            Some("0.1.4-alpha.1")
        );
        assert_eq!(normalize_tag("v0.1.4"), None);
        assert_eq!(normalize_tag("0.1.4"), None);
        assert_eq!(normalize_tag("byok-vgarbage"), None);
        assert_eq!(normalize_tag("byok-v"), None);
        assert_eq!(normalize_tag(""), None);
    }

    #[test]
    fn normalize_pin_accepts_all_spellings() {
        assert_eq!(normalize_pin("byok-v0.1.4"), "0.1.4");
        assert_eq!(normalize_pin("v0.1.4"), "0.1.4");
        assert_eq!(normalize_pin("0.1.4"), "0.1.4");
        assert_eq!(normalize_pin("  byok-v0.1.4  "), "0.1.4");
        assert_eq!(normalize_pin("garbage"), "garbage");
    }

    #[test]
    fn pick_latest_is_semver_max_not_date_order() {
        let tags = vec![
            "byok-v0.1.2".to_string(),
            "v1.0.0".to_string(),
            "byok-v0.1.10".to_string(),
            "byok-vgarbage".to_string(),
            "byok-v0.1.9".to_string(),
        ];
        assert_eq!(pick_latest(&tags).as_deref(), Some("0.1.10"));
        let none: Vec<String> = vec!["v1.0.0".to_string()];
        assert_eq!(pick_latest(&none), None);
    }

    #[test]
    fn pick_latest_skips_prereleases() {
        let tags = vec![
            "byok-v0.1.8".to_string(),
            "byok-v0.2.0-rc1".to_string(),
            "byok-v0.2.0-alpha.1".to_string(),
        ];
        assert_eq!(pick_latest(&tags).as_deref(), Some("0.1.8"));
        // No stable release at all: nothing to pick, never serve a prerelease.
        let only_prerelease: Vec<String> = vec!["byok-v0.2.0-rc1".to_string()];
        assert_eq!(pick_latest(&only_prerelease), None);
    }

    #[test]
    fn is_sha256_hex_accepts_only_64_hex_chars() {
        assert!(is_sha256_hex(&"a".repeat(64)));
        assert!(is_sha256_hex(&"F".repeat(64)));
        assert!(is_sha256_hex(&format!("{}9", "0".repeat(63))));
        assert!(!is_sha256_hex(&"g".repeat(64)));
        assert!(!is_sha256_hex(&"a".repeat(63)));
        assert!(!is_sha256_hex(&"a".repeat(65)));
        assert!(!is_sha256_hex(""));
    }
}
